services:
  db:
    image: postgres:17.1-alpine
    container_name: rudder_db
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: unless-stopped
