// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountClassT string

const (
	AccountClassTAsset     AccountClassT = "Asset"
	AccountClassTLiability AccountClassT = "Liability"
)

func (e *AccountClassT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountClassT(s)
	case string:
		*e = AccountClassT(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountClassT: %T", src)
	}
	return nil
}

type NullAccountClassT struct {
	AccountClassT AccountClassT
	Valid         bool // Valid is true if AccountClassT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountClassT) Scan(value interface{}) error {
	if value == nil {
		ns.AccountClassT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountClassT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountClassT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountClassT), nil
}

type AccountTypeT string

const (
	AccountTypeTCHECKING AccountTypeT = "CHECKING"
	AccountTypeTSAVINGS  AccountTypeT = "SAVINGS"
	AccountTypeTCREDIT   AccountTypeT = "CREDIT"
	AccountTypeTVENMO    AccountTypeT = "VENMO"
)

func (e *AccountTypeT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountTypeT(s)
	case string:
		*e = AccountTypeT(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountTypeT: %T", src)
	}
	return nil
}

type NullAccountTypeT struct {
	AccountTypeT AccountTypeT
	Valid        bool // Valid is true if AccountTypeT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountTypeT) Scan(value interface{}) error {
	if value == nil {
		ns.AccountTypeT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountTypeT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountTypeT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountTypeT), nil
}

type AutocatCriteriaOperatorT string

const (
	AutocatCriteriaOperatorTEquals     AutocatCriteriaOperatorT = "equals"
	AutocatCriteriaOperatorTContains   AutocatCriteriaOperatorT = "contains"
	AutocatCriteriaOperatorTStartsWith AutocatCriteriaOperatorT = "starts_with"
	AutocatCriteriaOperatorTEndsWith   AutocatCriteriaOperatorT = "ends_with"
	AutocatCriteriaOperatorTRegex      AutocatCriteriaOperatorT = "regex"
	AutocatCriteriaOperatorTPolarity   AutocatCriteriaOperatorT = "polarity"
	AutocatCriteriaOperatorTMin        AutocatCriteriaOperatorT = "min"
	AutocatCriteriaOperatorTMax        AutocatCriteriaOperatorT = "max"
)

func (e *AutocatCriteriaOperatorT) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AutocatCriteriaOperatorT(s)
	case string:
		*e = AutocatCriteriaOperatorT(s)
	default:
		return fmt.Errorf("unsupported scan type for AutocatCriteriaOperatorT: %T", src)
	}
	return nil
}

type NullAutocatCriteriaOperatorT struct {
	AutocatCriteriaOperatorT AutocatCriteriaOperatorT
	Valid                    bool // Valid is true if AutocatCriteriaOperatorT is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAutocatCriteriaOperatorT) Scan(value interface{}) error {
	if value == nil {
		ns.AutocatCriteriaOperatorT, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AutocatCriteriaOperatorT.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAutocatCriteriaOperatorT) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AutocatCriteriaOperatorT), nil
}

type Account struct {
	ID           int64
	AccountID    string
	AccountName  string
	InstName     string
	AccountType  NullAccountTypeT
	AccountClass NullAccountClassT
	Currency     string
	Active       bool
}

type AutocatCriterium struct {
	ID                     int64
	RuleID                 int32
	ColumnName             string
	Operator               AutocatCriteriaOperatorT
	FilterValueText        pgtype.Text
	FilterValueNumeric     pgtype.Numeric
	FilterValueTimestamptz pgtype.Timestamptz
	CriteriaOrder          pgtype.Int4
}

type AutocatOverride struct {
	ID            int64
	RuleID        int64
	ColumnName    string
	OverrideValue string
	OverrideOrder int32
}

type AutocatRule struct {
	ID        int64
	Priority  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Balance struct {
	ID          int64
	BalanceID   string
	BalanceDate pgtype.Timestamptz
	Balance     pgtype.Numeric
	AccountID   string
	AddedDate   pgtype.Timestamptz
}

type Category struct {
	ID              int64
	Category        string
	CategoryGroup   string
	CategoryType    string
	BusinessExpense bool
	HideFromReports bool
}

type Organization struct {
	ID         int64
	InstName   string
	SfinUrl    string
	DomainName pgtype.Text
	Url        pgtype.Text
}

type Transaction struct {
	ID              int64
	TransactionID   string
	PostedDate      pgtype.Timestamptz
	Description     pgtype.Text
	Category        pgtype.Text
	Amount          pgtype.Numeric
	AccountID       string
	InstName        string
	FullDescription string
	AddedDate       pgtype.Timestamptz
	CategorizedDate pgtype.Timestamptz
	Note            pgtype.Text
	CheckNum        pgtype.Text
}

type TransactionsCol struct {
	ColumnName string
	DataType   string
}
