// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAutocatRules = `-- name: GetAutocatRules :many
select (
        select json_agg (
                json_build_object (
                    'column_name',
                    c.column_name,
                    'operator',
                    c."operator",
                    'filter_value_text',
                    c.filter_value_text,
                    'filter_value_numeric',
                    c.filter_value_numeric,
                    'filter_value_timestamptz',
                    c.filter_value_timestamptz,
                    'criteria_order',
                    c.criteria_order
                )
            )
        from autocat_criteria c
        where c.rule_id = r.id
    ) as criteria,
    (
        select json_agg (
                json_build_object (
                    'column_name',
                    o.column_name,
                    'override_value',
                    o.override_value,
                    'override_order',
                    o.override_order
                )
            )
        from autocat_overrides o
        where o.rule_id = r.id
    ) as overrides
from autocat_rules r
`

type GetAutocatRulesRow struct {
	Criteria  []byte
	Overrides []byte
}

func (q *Queries) GetAutocatRules(ctx context.Context) ([]GetAutocatRulesRow, error) {
	rows, err := q.db.Query(ctx, getAutocatRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAutocatRulesRow
	for rows.Next() {
		var i GetAutocatRulesRow
		if err := rows.Scan(&i.Criteria, &i.Overrides); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionRows = `-- name: GetTransactionRows :many
select transaction_id,
    posted_date,
    description,
    category,
    amount,
    account_id,
    inst_name,
    full_description,
    added_date,
    categorized_date,
    note,
    check_num
from transactions
`

type GetTransactionRowsRow struct {
	TransactionID   string
	PostedDate      pgtype.Timestamptz
	Description     pgtype.Text
	Category        pgtype.Text
	Amount          pgtype.Numeric
	AccountID       string
	InstName        string
	FullDescription string
	AddedDate       pgtype.Timestamptz
	CategorizedDate pgtype.Timestamptz
	Note            pgtype.Text
	CheckNum        pgtype.Text
}

func (q *Queries) GetTransactionRows(ctx context.Context) ([]GetTransactionRowsRow, error) {
	rows, err := q.db.Query(ctx, getTransactionRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionRowsRow
	for rows.Next() {
		var i GetTransactionRowsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.PostedDate,
			&i.Description,
			&i.Category,
			&i.Amount,
			&i.AccountID,
			&i.InstName,
			&i.FullDescription,
			&i.AddedDate,
			&i.CategorizedDate,
			&i.Note,
			&i.CheckNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccounts = `-- name: InsertAccounts :one
with rows as (
    insert into accounts (account_id, account_name, inst_name, currency)
    values ($1, $2, $3, $4) on conflict do nothing
    returning 1
)
select count(*)
from rows
`

type InsertAccountsParams struct {
	AccountID   string
	AccountName string
	InstName    string
	Currency    string
}

func (q *Queries) InsertAccounts(ctx context.Context, arg InsertAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAccounts,
		arg.AccountID,
		arg.AccountName,
		arg.InstName,
		arg.Currency,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertBalances = `-- name: InsertBalances :one
with rows as (
    insert into balances (balance_id, balance_date, balance, account_id)
    values ($1, $2, $3, $4) on conflict do nothing
    returning 1
)
select count(*)
from rows
`

type InsertBalancesParams struct {
	BalanceID   string
	BalanceDate pgtype.Timestamptz
	Balance     pgtype.Numeric
	AccountID   string
}

func (q *Queries) InsertBalances(ctx context.Context, arg InsertBalancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBalances,
		arg.BalanceID,
		arg.BalanceDate,
		arg.Balance,
		arg.AccountID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertOrganizations = `-- name: InsertOrganizations :one
with rows as (
    insert into organizations (inst_name, sfin_url, domain_name, url)
    values ($1, $2, $3, $4) on conflict do nothing
    returning 1
)
select count(*)
from rows
`

type InsertOrganizationsParams struct {
	InstName   string
	SfinUrl    string
	DomainName pgtype.Text
	Url        pgtype.Text
}

func (q *Queries) InsertOrganizations(ctx context.Context, arg InsertOrganizationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrganizations,
		arg.InstName,
		arg.SfinUrl,
		arg.DomainName,
		arg.Url,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertTransactions = `-- name: InsertTransactions :one
with rows as (
    insert into transactions (
            transaction_id,
            posted_date,
            description,
            amount,
            account_id,
            inst_name,
            full_description
        )
    values ($1, $2, $3, $4, $5, $6, $7) on conflict do nothing
    returning 1
)
select count(*)
from rows
`

type InsertTransactionsParams struct {
	TransactionID   string
	PostedDate      pgtype.Timestamptz
	Description     pgtype.Text
	Amount          pgtype.Numeric
	AccountID       string
	InstName        string
	FullDescription string
}

func (q *Queries) InsertTransactions(ctx context.Context, arg InsertTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTransactions,
		arg.TransactionID,
		arg.PostedDate,
		arg.Description,
		arg.Amount,
		arg.AccountID,
		arg.InstName,
		arg.FullDescription,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTransactionCategories = `-- name: UpdateTransactionCategories :one
with rows as (
    update transactions
    set category = $2,
        categorized_date = $3
    where transaction_id = $1
        and category is null
    returning 1
)
select count(*)
from rows
`

type UpdateTransactionCategoriesParams struct {
	TransactionID   string
	Category        pgtype.Text
	CategorizedDate pgtype.Timestamptz
}

func (q *Queries) UpdateTransactionCategories(ctx context.Context, arg UpdateTransactionCategoriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateTransactionCategories, arg.TransactionID, arg.Category, arg.CategorizedDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}
